// =============================================
// SANZCREATIVE ALR — Demo Data
// Clearly labelled for development use only
// =============================================

import type { Client, Campaign, Lead, LeadNote, LeadStatusHistory } from '@/types'

export const DEMO_CLIENTS: Client[] = [
  {
    id: 'demo-client-1',
    name: 'VTK Citroën',
    business_category: 'Automotive Dealership',
    contact_person: 'Ravi Kumar',
    email: 'ravi@vtkcars.com',
    phone: '+91 98765 43210',
    status: 'active',
    created_at: '2024-11-01T09:00:00Z',
  },
  {
    id: 'demo-client-2',
    name: 'Harini Nails',
    business_category: 'Beauty & Wellness',
    contact_person: 'Harini Priya',
    email: 'harini@harininails.com',
    phone: '+91 87654 32109',
    status: 'active',
    created_at: '2024-11-15T10:30:00Z',
  },
  {
    id: 'demo-client-3',
    name: 'Prestige Realty',
    business_category: 'Real Estate',
    contact_person: 'Suresh Babu',
    email: 'suresh@prestigerealty.in',
    phone: '+91 76543 21098',
    status: 'active',
    created_at: '2024-12-01T08:00:00Z',
  },
]

export const DEMO_CAMPAIGNS: Campaign[] = [
  {
    id: 'demo-campaign-1',
    client_id: 'demo-client-1',
    campaign_name: 'Citroën C3 Launch — Jan 2025',
    platform: 'facebook',
    meta_page_id: null,
    meta_form_id: null,
    status: 'active',
    created_at: '2025-01-05T09:00:00Z',
    client: DEMO_CLIENTS[0],
    lead_count: 47,
  },
  {
    id: 'demo-campaign-2',
    client_id: 'demo-client-1',
    campaign_name: 'Test Drive Offer — Feb 2025',
    platform: 'instagram',
    meta_page_id: null,
    meta_form_id: null,
    status: 'active',
    created_at: '2025-02-01T09:00:00Z',
    client: DEMO_CLIENTS[0],
    lead_count: 23,
  },
  {
    id: 'demo-campaign-3',
    client_id: 'demo-client-2',
    campaign_name: 'Valentine Nail Art — Feb 2025',
    platform: 'instagram',
    meta_page_id: null,
    meta_form_id: null,
    status: 'completed',
    created_at: '2025-02-05T10:00:00Z',
    client: DEMO_CLIENTS[1],
    lead_count: 61,
  },
  {
    id: 'demo-campaign-4',
    client_id: 'demo-client-2',
    campaign_name: 'New Branch Opening Offer',
    platform: 'both',
    meta_page_id: null,
    meta_form_id: null,
    status: 'active',
    created_at: '2025-03-01T08:00:00Z',
    client: DEMO_CLIENTS[1],
    lead_count: 38,
  },
  {
    id: 'demo-campaign-5',
    client_id: 'demo-client-3',
    campaign_name: 'Luxury Apartments — Phase 2',
    platform: 'facebook',
    meta_page_id: null,
    meta_form_id: null,
    status: 'active',
    created_at: '2025-01-20T09:00:00Z',
    client: DEMO_CLIENTS[2],
    lead_count: 89,
  },
]

export const DEMO_LEADS: Lead[] = [
  {
    id: 'demo-lead-1',
    client_id: 'demo-client-1',
    campaign_id: 'demo-campaign-1',
    meta_lead_id: null,
    full_name: 'Arjun Mehta',
    phone: '+91 99001 23456',
    email: 'arjun.mehta@gmail.com',
    source: 'Facebook Lead Ad',
    raw_form_data: {
      'What model are you interested in?': 'Citroën C3',
      'Preferred color': 'Platinum Silver',
      'When are you looking to purchase?': 'Within 1 month',
    },
    status: 'contacted',
    assigned_user_id: null,
    created_at: '2025-01-08T11:23:00Z',
    updated_at: '2025-01-09T09:00:00Z',
    client: DEMO_CLIENTS[0],
    campaign: DEMO_CAMPAIGNS[0],
  },
  {
    id: 'demo-lead-2',
    client_id: 'demo-client-1',
    campaign_id: 'demo-campaign-1',
    meta_lead_id: null,
    full_name: 'Priya Nair',
    phone: '+91 88112 34567',
    email: 'priya.nair@yahoo.com',
    source: 'Facebook Lead Ad',
    raw_form_data: {
      'What model are you interested in?': 'Citroën C3',
      'Preferred color': 'Red Magma',
      'When are you looking to purchase?': '3–6 months',
    },
    status: 'new',
    assigned_user_id: null,
    created_at: '2025-01-09T14:05:00Z',
    updated_at: '2025-01-09T14:05:00Z',
    client: DEMO_CLIENTS[0],
    campaign: DEMO_CAMPAIGNS[0],
  },
  {
    id: 'demo-lead-3',
    client_id: 'demo-client-1',
    campaign_id: 'demo-campaign-2',
    meta_lead_id: null,
    full_name: 'Kiran Raj',
    phone: '+91 77223 45678',
    email: null,
    source: 'Instagram Lead Ad',
    raw_form_data: {
      'Are you interested in a test drive?': 'Yes',
      'Nearest city': 'Chennai',
    },
    status: 'follow_up',
    assigned_user_id: null,
    created_at: '2025-02-03T09:47:00Z',
    updated_at: '2025-02-05T10:00:00Z',
    client: DEMO_CLIENTS[0],
    campaign: DEMO_CAMPAIGNS[1],
  },
  {
    id: 'demo-lead-4',
    client_id: 'demo-client-1',
    campaign_id: 'demo-campaign-1',
    meta_lead_id: null,
    full_name: 'Deepa Suresh',
    phone: '+91 66334 56789',
    email: 'deepa.suresh@outlook.com',
    source: 'Facebook Lead Ad',
    raw_form_data: {
      'What model are you interested in?': 'Citroën C3',
      'Preferred color': 'Steel Grey',
      'When are you looking to purchase?': 'Within 1 month',
    },
    status: 'converted',
    assigned_user_id: null,
    created_at: '2025-01-10T16:20:00Z',
    updated_at: '2025-01-22T11:00:00Z',
    client: DEMO_CLIENTS[0],
    campaign: DEMO_CAMPAIGNS[0],
  },
  {
    id: 'demo-lead-5',
    client_id: 'demo-client-2',
    campaign_id: 'demo-campaign-3',
    meta_lead_id: null,
    full_name: 'Meena Krishnan',
    phone: '+91 55445 67890',
    email: 'meena.k@gmail.com',
    source: 'Instagram Lead Ad',
    raw_form_data: {
      'Nail art style preferred': 'Gel Extensions',
      'Occasion': 'Valentine\'s Day',
      'Preferred date': 'Feb 12–14',
    },
    status: 'interested',
    assigned_user_id: null,
    created_at: '2025-02-07T12:10:00Z',
    updated_at: '2025-02-08T09:00:00Z',
    client: DEMO_CLIENTS[1],
    campaign: DEMO_CAMPAIGNS[2],
  },
  {
    id: 'demo-lead-6',
    client_id: 'demo-client-2',
    campaign_id: 'demo-campaign-4',
    meta_lead_id: null,
    full_name: 'Sunitha Pillai',
    phone: '+91 44556 78901',
    email: 'sunitha.pillai@gmail.com',
    source: 'Facebook Lead Ad',
    raw_form_data: {
      'Service interested in': 'Manicure + Pedicure Combo',
      'New branch location': 'Anna Nagar',
    },
    status: 'new',
    assigned_user_id: null,
    created_at: '2025-03-05T10:30:00Z',
    updated_at: '2025-03-05T10:30:00Z',
    client: DEMO_CLIENTS[1],
    campaign: DEMO_CAMPAIGNS[3],
  },
  {
    id: 'demo-lead-7',
    client_id: 'demo-client-3',
    campaign_id: 'demo-campaign-5',
    meta_lead_id: null,
    full_name: 'Venkat Raman',
    phone: '+91 33667 89012',
    email: 'venkat.r@gmail.com',
    source: 'Facebook Lead Ad',
    raw_form_data: {
      'Budget range': '₹80L – ₹1.2Cr',
      'Bedrooms required': '3 BHK',
      'Ready to move in': 'Yes',
      'Looking to book site visit?': 'This weekend',
    },
    status: 'contacted',
    assigned_user_id: null,
    created_at: '2025-01-22T08:45:00Z',
    updated_at: '2025-01-23T14:00:00Z',
    client: DEMO_CLIENTS[2],
    campaign: DEMO_CAMPAIGNS[4],
  },
  {
    id: 'demo-lead-8',
    client_id: 'demo-client-3',
    campaign_id: 'demo-campaign-5',
    meta_lead_id: null,
    full_name: 'Anjali Devi',
    phone: '+91 22778 90123',
    email: 'anjali.devi@hotmail.com',
    source: 'Facebook Lead Ad',
    raw_form_data: {
      'Budget range': '₹60L – ₹80L',
      'Bedrooms required': '2 BHK',
      'Ready to move in': 'No, under construction preferred',
      'Looking to book site visit?': 'Next week',
    },
    status: 'not_interested',
    assigned_user_id: null,
    created_at: '2025-01-25T15:30:00Z',
    updated_at: '2025-01-28T10:00:00Z',
    client: DEMO_CLIENTS[2],
    campaign: DEMO_CAMPAIGNS[4],
  },
]

export const DEMO_NOTES: LeadNote[] = [
  {
    id: 'demo-note-1',
    lead_id: 'demo-lead-1',
    user_id: 'demo-admin',
    note: 'Called customer. Very interested in the C3 Platinum Silver. Sending brochure and EMI details via WhatsApp.',
    created_at: '2025-01-09T09:05:00Z',
  },
  {
    id: 'demo-note-2',
    lead_id: 'demo-lead-7',
    user_id: 'demo-admin',
    note: 'Site visit booked for Sunday 26th Jan at 10am. Interested in Tower B, 3rd floor units.',
    created_at: '2025-01-23T14:15:00Z',
  },
]

export const DEMO_STATUS_HISTORY: LeadStatusHistory[] = [
  {
    id: 'demo-hist-1',
    lead_id: 'demo-lead-4',
    old_status: 'new',
    new_status: 'contacted',
    changed_by: 'demo-admin',
    created_at: '2025-01-11T09:00:00Z',
  },
  {
    id: 'demo-hist-2',
    lead_id: 'demo-lead-4',
    old_status: 'contacted',
    new_status: 'interested',
    changed_by: 'demo-admin',
    created_at: '2025-01-14T14:00:00Z',
  },
  {
    id: 'demo-hist-3',
    lead_id: 'demo-lead-4',
    old_status: 'interested',
    new_status: 'converted',
    changed_by: 'demo-admin',
    created_at: '2025-01-22T11:00:00Z',
  },
]

export const DEMO_STATS = {
  total_clients: 3,
  total_leads: 258,
  new_leads: 47,
  contacted_leads: 89,
  follow_up_leads: 34,
  converted_leads: 31,
  conversion_rate: 12.0,
}

export const DEMO_LEADS_OVER_TIME = [
  { date: 'Jan 1', count: 8 },
  { date: 'Jan 8', count: 14 },
  { date: 'Jan 15', count: 11 },
  { date: 'Jan 22', count: 19 },
  { date: 'Jan 29', count: 16 },
  { date: 'Feb 5', count: 22 },
  { date: 'Feb 12', count: 31 },
  { date: 'Feb 19', count: 27 },
  { date: 'Feb 26', count: 18 },
  { date: 'Mar 5', count: 24 },
  { date: 'Mar 12', count: 29 },
  { date: 'Mar 19', count: 39 },
]
